-- Auto-generated by cambrian-transpiler. Do not edit.
-- Library root: re-imports the vendored prelude and every
-- generated entity so `lake build` builds the full project.
import Cambrian.Prelude
import Cambrian.Generated.Pure
import Cambrian.Generated.ERC20
import Cambrian.Generated.UniswapV2Pair
import Cambrian.Generated.UniswapV2Factory
import Cambrian.Generated.World
import Cambrian.Generated.Dispatch
import Cambrian.Generated.ERC20Routes
import Cambrian.Generated.UniswapV2PairRoutes
import Cambrian.Generated.UniswapV2FactoryRoutes
