-- Auto-generated by cambrian-transpiler. Do not edit.
-- Library root: re-imports the vendored prelude and every
-- generated entity so `lake build` builds the full project.
import Cambrian.Prelude
import Cambrian.Generated.Counter
import Cambrian.Generated.World
import Cambrian.Generated.CounterRoutes
