// Copyright (C) 2025-2026 The Cambrian Authors
// SPDX-License-Identifier: GPL-3.0-only

//! Lean codegen — per-program `Cambrian.Generated.World` (P3.3).
//!
//! Emits a single `Cambrian/Generated/World.lean` file containing:
//!
//! * `Cambrian.Generated.Storage` — uniform record with one field per
//!   declared entity, typed `<Entity>.Identity → <Entity>.State`.
//!   Singletons use the empty `Identity` (uniform signature).
//! * `Cambrian.Generated.World` — abbreviation for
//!   `Cambrian.WorldState Cambrian.Generated.Storage`.
//! * `World.default` — factory producing the empty world (every entity
//!   slot maps every identity to `<E>.State.default`; zero balances;
//!   `BlockEnv.default`).
//! * Per-entity projection / setter:
//!     * `World.<entityLower> (w : World) (id : <E>.Identity) : <E>.State`
//!     * `World.with<Entity> (w : World) (id : <E>.Identity) (s : <E>.State) : World`
//!
//! This module is purely structural — it does not depend on whether
//! the entity has routes, members, or tests; every entity reachable
//! from the program is included so route entry-points (P3.5) and
//! spec theorems (P3.7) can thread the same `World`.

use crate::ast::{Entity, EventDecl, Program};

use super::super::core::types::{lean_safe_ident, lower_type, LeanTypeCtx};

/// Generate `Cambrian/Generated/World.lean` for a program. Always
/// emits — programs with zero entities still get a (mostly trivial)
/// `Storage` / `World` pair so library-root imports never fan into
/// nothing.
pub fn gen_world_module(program: &Program, profile: super::super::LeanProfile) -> String {
    let mut out = String::new();
    out.push_str("/-\n");
    out.push_str("  Auto-generated by cambrian-transpiler — Lean target (P3).\n");
    out.push_str("  Per-program World carrier:\n");
    out.push_str("    Storage = record of (Identity → State) maps, one per entity\n");
    out.push_str("    World   = Cambrian.WorldState Storage\n");
    out.push_str("-/\n\n");

    out.push_str("import Cambrian.Prelude\n");
    for e in &program.entities {
        out.push_str(&format!("import Cambrian.Generated.{}\n", e.name));
    }
    out.push('\n');

    out.push_str("set_option linter.unusedVariables false\n\n");

    out.push_str("namespace Cambrian.Generated\n\n");

    // Storage record.
    out.push_str("/-- Per-program storage. Uniform across all entities: every entity\n");
    out.push_str("    (singleton or multi-instance) gets a slot keyed by its `Identity`. -/\n");
    out.push_str("structure Storage where\n");
    if program.entities.is_empty() {
        // Lean accepts empty `structure ... where deriving ...`, but
        // having no entities means no `World.with*` either; keep the
        // structure declarable.
    } else {
        for e in &program.entities {
            let field = entity_field_name(&e.name);
            let deployed = entity_deployed_field_name(&e.name);
            out.push_str(&format!(
                "  {} : {}.Identity → {}.State\n",
                field, e.name, e.name,
            ));
            // Occupancy flag: CREATE2-style deploy must not overwrite an
            // already-live identity (T-X-001 / LEAN-H5). Separate from
            // `State` so a default-valued install is still distinguishable.
            out.push_str(&format!("  {} : {}.Identity → Bool\n", deployed, e.name,));
        }
    }
    out.push('\n');

    // Ghost event-log element type.
    gen_event_inductive(program, &mut out, profile);

    out.push_str("/-- World carrier specialised to this program's storage and event log. -/\n");
    out.push_str("abbrev World := Cambrian.WorldState Storage Event\n\n");

    // Storage.default — every identity maps to <E>.State.default.
    out.push_str("/-- Canonical empty storage. Every entity slot maps every identity\n");
    out.push_str("    to that entity's `State.default`. -/\n");
    out.push_str("def Storage.default : Storage :=\n");
    if program.entities.is_empty() {
        out.push_str("  {}\n\n");
    } else {
        out.push_str("  {\n");
        for e in &program.entities {
            let field = entity_field_name(&e.name);
            let deployed = entity_deployed_field_name(&e.name);
            out.push_str(&format!(
                "    {} := fun _ => {}.State.default\n",
                field, e.name,
            ));
            out.push_str(&format!("    {} := fun _ => false\n", deployed,));
        }
        out.push_str("  }\n\n");
    }

    // World.default.
    out.push_str("/-- Canonical empty world: empty storage, zero balances, default\n");
    out.push_str("    block environment. Spec theorems start here and apply\n");
    out.push_str("    `World.with<Entity>` to seed concrete instances. -/\n");
    out.push_str("def World.default : World :=\n");
    out.push_str("  { storage  := Storage.default\n");
    out.push_str("    balances := fun _ => 0#256\n");
    out.push_str("    block    := Cambrian.BlockEnv.default\n");
    out.push_str("    events   := [] }\n\n");

    // `Inhabited` instance so opaque axioms returning `World × T`
    // (dispatch / extern) typecheck.
    out.push_str("instance : Inhabited World := ⟨World.default⟩\n\n");

    // Per-entity projections + setters.
    for e in &program.entities {
        let field = entity_field_name(&e.name);
        let getter = format!("World.{}", field);
        let setter = format!("World.with{}", e.name);
        out.push_str(&format!(
            "/-- Look up the `{0}` instance at `id` (defaults to `{0}.State.default` if\n    no setter has touched that slot yet). -/\n",
            e.name,
        ));
        out.push_str(&format!(
            "def {getter} (w : World) (id : {ename}.Identity) : {ename}.State :=\n  w.storage.{field} id\n\n",
            getter = getter, ename = e.name, field = field,
        ));
        out.push_str(&format!(
            "/-- Functional update: replace the `{0}` slot at `id` with `s` and\n    mark that identity as deployed (CREATE2 occupancy). -/\n",
            e.name,
        ));
        out.push_str(&format!(
            "def {setter} (w : World) (id : {ename}.Identity) (s : {ename}.State) : World :=\n",
            setter = setter,
            ename = e.name,
        ));
        out.push_str(&format!(
            "  {{ w with storage := {{ w.storage with\n\
             \x20     {field} := fun id' => if id' = id then s else w.storage.{field} id'\n\
             \x20     {deployed} := fun id' => if id' = id then true else w.storage.{deployed} id' }} }}\n\n",
            field = field,
            deployed = entity_deployed_field_name(&e.name),
        ));
    }

    out.push_str("end Cambrian.Generated\n");
    out
}

/// Emit the per-program `Cambrian.Generated.Event` inductive — one
/// constructor per declared `event`. Program-scope events keep their
/// bare name; entity-scope events are prefixed with the entity name so
/// constructors stay unique across entities (and across scopes). The
/// constructor carries one field per event parameter, lowered to its
/// Lean type. Programs with no events get an empty inductive (the
/// ghost log then stays `[]` forever).
fn gen_event_inductive(program: &Program, out: &mut String, profile: super::super::LeanProfile) {
    out.push_str(
        "/-- Ghost event-log element type: one constructor per declared `event`.\n    \
         Entity-scope events are prefixed with the entity name; program-scope\n    \
         events keep their bare name. Used by `Cambrian.WorldState.emit`. -/\n",
    );

    let mut ctors: Vec<String> = Vec::new();
    for ev in &program.events {
        ctors.push(format!(
            "  | {}",
            event_ctor_decl(program, None, ev, profile)
        ));
    }
    for e in &program.entities {
        for ev in &e.events {
            ctors.push(format!(
                "  | {}",
                event_ctor_decl(program, Some(e), ev, profile)
            ));
        }
    }

    if ctors.is_empty() {
        // Empty inductive — no `where` clause (an empty `where` block is
        // a parse error in Lean 4).
        out.push_str("inductive Event\n\n");
        return;
    }
    out.push_str("inductive Event where\n");
    for c in &ctors {
        out.push_str(c);
        out.push('\n');
    }
    out.push('\n');
}

/// Render one `Event` constructor declaration (without the leading
/// `| `): `<CtorName> (p₀ : T₀) (p₁ : T₁) …`.
fn event_ctor_decl(
    program: &Program,
    entity: Option<&Entity>,
    ev: &EventDecl,
    profile: super::super::LeanProfile,
) -> String {
    let ctx = event_type_ctx(program, entity, profile);
    let fields: Vec<String> = ev
        .params
        .iter()
        .map(|p| {
            format!(
                "({} : {})",
                lean_safe_ident(&p.name),
                lower_type(&p.ty, &ctx)
            )
        })
        .collect();
    let name = event_ctor_name(entity, &ev.name);
    if fields.is_empty() {
        name
    } else {
        format!("{} {}", name, fields.join(" "))
    }
}

fn event_type_ctx<'a>(
    program: &'a Program,
    entity: Option<&'a Entity>,
    profile: super::super::LeanProfile,
) -> LeanTypeCtx<'a> {
    match entity {
        Some(e) => LeanTypeCtx::for_entity(
            program,
            &e.name,
            &e.records,
            &e.enums,
            &e.type_aliases,
            profile,
        ),
        None => LeanTypeCtx::for_entity(program, "", &[], &[], &[], profile),
    }
}

/// The `Cambrian.Generated.Event` constructor name for an `event`
/// declared at `entity` scope (`Some`) or program scope (`None`).
/// Shared with route codegen so `emit Name(args)` lowers to the same
/// constructor the inductive declares.
pub fn event_ctor_name(entity: Option<&Entity>, event_name: &str) -> String {
    match entity {
        Some(e) => format!("{}_{}", e.name, event_name),
        None => event_name.to_string(),
    }
}

/// Resolve `emit <event_name>` inside `entity` to its `Event`
/// constructor name. Entity-scope declarations shadow program-scope
/// ones (mirrors the EVM/validator resolution order). Returns `None`
/// when the event is undeclared (validator `V34` should have caught
/// this earlier).
pub fn resolve_event_ctor(program: &Program, entity: &Entity, event_name: &str) -> Option<String> {
    if entity.events.iter().any(|e| e.name == event_name) {
        return Some(event_ctor_name(Some(entity), event_name));
    }
    if program.events.iter().any(|e| e.name == event_name) {
        return Some(event_ctor_name(None, event_name));
    }
    None
}

/// Lowercase the first character of an entity name to produce a
/// stable, Lean-idiomatic field name (`Counter` → `counter`,
/// `LendingPair` → `lendingPair`). Pure ASCII; we never see Unicode
/// entity names.
pub fn entity_field_name(entity_name: &str) -> String {
    let mut chars = entity_name.chars();
    match chars.next() {
        Some(c) => c.to_ascii_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

/// Storage field tracking CREATE2-style occupancy for `entity_name`
/// (`Vault` → `vault_deployed`).
pub fn entity_deployed_field_name(entity_name: &str) -> String {
    format!("{}_deployed", entity_field_name(entity_name))
}
