# Copyright (C) 2025-2026 The Cambrian Authors
# SPDX-License-Identifier: GPL-3.0-only

name: test-dapp
target: evm
deterministic_addresses: true
output_dir: build/
sources:
  - proj_counter.cam
  - proj_vault.cam
