// Copyright (C) 2025-2026 The Cambrian Authors
// SPDX-License-Identifier: GPL-3.0-only

//! Lean codegen — Entity → Lean namespace + State + Identity + locals (P1.2).
//!
//! Replaces the P0 stub with a real emission of:
//!
//! * locally-declared `record` / `enum` / `type alias` / `const` items
//!   (in declaration order — matches Lean's name-resolution top-down);
//! * `<Entity>.State` populated with all members (identity + non-identity)
//!   typed via [`lean_types::lower_type`];
//! * `<Entity>.Identity` populated with the identity members only;
//! * `<Entity>.State.identity` projecting them out — even when there are
//!   no identity members, so P3 can plug in `Entity.address` uniformly;
//! * `<Entity>.State.default` filling each non-identity member from
//!   [`lean_types::default_for_type`] (or from its declared default
//!   expression when one is present).
//!
//! Member transforms and route assemblers live in
//! [`lean_member`](super::member) and [`lean_route`](super::route)
//! respectively; this module only emits the structural surface plus
//! constants and local types.

use std::collections::HashSet;

use crate::ast::{Entity, EnumDecl, EnumVariant, Program, Record, TypeAlias};

use super::core::emitter::{doc_comment, line_comment, push_deriving, push_indent};
use super::core::route_local::emit_macro_helpers;
use super::core::state::{emit_identity_struct, emit_state_default, emit_state_struct};
use super::core::types::{lean_local_type_name, lower_type, sanitize_variant, LeanTypeCtx};
use super::evm::address::emit_address;
use super::expr::{gen_expr, LeanExprCtx};
use super::member::gen_member_module;
use super::LeanProfile;

/// Emit the full Lean file for `entity` under `program`. The file is
/// self-contained — it imports `Cambrian.Prelude` and (when needed)
/// `Cambrian.Generated.Pure`. Top-level program records / enums /
/// aliases reachable from this entity's bodies are emitted in the
/// project root (handled by [`super::LeanBackend`]); we only
/// emit the entity-local copies here.
pub fn gen_entity(program: &Program, entity: &Entity, profile: LeanProfile) -> String {
    let mut out = String::new();

    let identity_count = entity.members.iter().filter(|m| m.is_identity).count();
    let state_count = entity.members.iter().filter(|m| !m.is_identity).count();
    let route_count = entity.routes.len();

    out.push_str("/-\n");
    out.push_str("  Auto-generated by cambrian-transpiler — Lean target (P1).\n");
    if profile.nat_numerics {
        out.push_str(
            "  numerics: nat (u* → Nat, i* → Int; overflow ignored — not EVM-bit-accurate)\n",
        );
    } else if profile.overflow_panic {
        out.push_str(
            "  numerics: overflow-panic (checked +/−/* → RouteResult; i* use checkedS*)\n",
        );
    }
    out.push_str(&format!("  Source entity: {}\n", entity.name));
    out.push_str(&format!(
        "  Members: {} identity + {} state. Routes: {}.\n",
        identity_count, state_count, route_count,
    ));
    out.push_str("-/\n\n");

    out.push_str("import Cambrian.Prelude\n");
    if super::core::pure::program_needs_pure_import(program) {
        out.push_str("import Cambrian.Generated.Pure\n");
    }
    // Cross-entity references in member transforms (e.g.
    // `UniswapV2Pair.address(t0, t1)`) need the other entity's state
    // module to be importable. Walk member-transform bodies to find
    // such references and emit the imports. Skip self-imports.
    let mut entity_refs = std::collections::BTreeSet::new();
    collect_entity_refs_in_entity(entity, program, &mut entity_refs);
    for ent_name in &entity_refs {
        if ent_name != &entity.name {
            out.push_str(&format!("import Cambrian.Generated.{}\n", ent_name));
        }
    }
    out.push('\n');

    // Generated route signatures often carry params (`s`, `ctx`,
    // unused destructuring slots) that the body doesn't reference.
    // Silence the warning per-file rather than touching every binder
    // — the noise hides genuine unused-binding bugs in user code.
    out.push_str("set_option linter.unusedVariables false\n\n");

    out.push_str(&format!("namespace {}\n\n", entity.name));

    emit_local_aliases(&mut out, entity, profile);
    emit_local_types_ordered(&mut out, program, entity, profile);
    emit_constants(&mut out, program, entity, profile);
    emit_state_struct(&mut out, program, entity, profile);
    emit_identity_struct(&mut out, program, entity, profile);
    emit_state_default(&mut out, program, entity, profile);
    emit_address(&mut out, entity, profile.nat_numerics);

    out.push_str(&format!("end {}\n\n", entity.name));

    // State-only macros live here (same file as Members) so a transform
    // can call `E.Local.macro_*` without importing Routes / World.
    let mut macros = String::new();
    if emit_macro_helpers(&mut macros, program, entity, profile, false) {
        out.push_str(&format!("namespace {}.Local\n\n", entity.name));
        out.push_str(&macros);
        out.push_str(&format!("end {}.Local\n\n", entity.name));
    }

    let member_block = gen_member_module(program, entity, profile);
    if !member_block.is_empty() {
        out.push_str(&member_block);
        out.push('\n');
    }

    if route_count == 0 && entity.members.iter().all(|m| m.transforms.is_empty()) {
        line_comment(
            &mut out,
            0,
            &format!(
                "Entity '{}' has no routes or transforms — only the state surface is emitted.",
                entity.name,
            ),
        );
    }

    out
}

/// Walk every member transform and the constructor route body of
/// `entity`, collecting references to in-program entity names that
/// appear in `<Entity>.address(args)` method-call positions. Used by
/// [`gen_entity`] to emit the matching `import Cambrian.Generated.<E>`
/// lines so cross-entity address derivations type-check.
fn collect_entity_refs_in_entity(
    entity: &Entity,
    program: &Program,
    out: &mut std::collections::BTreeSet<String>,
) {
    use crate::ast::Expr;
    fn walk(e: &Expr, program: &Program, out: &mut std::collections::BTreeSet<String>) {
        match e {
            Expr::MethodCall(base, name, args) => {
                // `<E>.address(args)` and `<E>.state(args)` (the latter
                // inside `addressOf(<E>.state(args))` and deploy
                // `stateInit`) both lower to `<E>.address` / `<E>.…`, so
                // either reference pulls in `<E>`'s state module.
                if name == "address" || name == "state" {
                    if let Expr::Ident(ent) = base.as_ref() {
                        if program.entities.iter().any(|e| &e.name == ent) {
                            out.insert(ent.clone());
                        }
                    }
                }
                walk(base, program, out);
                for a in args {
                    walk(a, program, out);
                }
            }
            Expr::FnCall(_, args) | Expr::Tuple(args) | Expr::EnumVariantWithData(_, _, args) => {
                for a in args {
                    walk(a, program, out);
                }
            }
            Expr::BinOp(l, _, r) => {
                walk(l, program, out);
                walk(r, program, out);
            }
            Expr::UnaryOp(_, x) | Expr::FieldAccess(x, _) | Expr::Index(x, _) | Expr::Some(x) => {
                walk(x, program, out)
            }
            Expr::If(c, t, el) => {
                walk(c, program, out);
                walk(t, program, out);
                if let Some(e) = el {
                    walk(e, program, out);
                }
            }
            Expr::Let(_, v, b) => {
                walk(v, program, out);
                walk(b, program, out);
            }
            Expr::Block(items) => {
                for x in items {
                    walk(x, program, out);
                }
            }
            Expr::RecordConstruct(_, fields) => {
                for (_, v) in fields {
                    walk(v, program, out);
                }
            }
            Expr::Match(s, arms) => {
                walk(s, program, out);
                for a in arms {
                    walk(&a.body, program, out);
                }
            }
            Expr::NamespacedCall { args, .. } => {
                for a in args {
                    walk(a, program, out);
                }
            }
            Expr::AddressOf {
                entity_name, args, ..
            } => {
                if program.entities.iter().any(|e| &e.name == entity_name) {
                    out.insert(entity_name.clone());
                }
                for a in args {
                    walk(a, program, out);
                }
            }
            _ => {}
        }
    }
    for m in &entity.members {
        for tr in &m.transforms {
            walk(&tr.body, program, out);
        }
    }
}

/// Generate the per-entity `<Entity>Routes.lean` file (P3.5+). Routes
/// now live in a separate Lean module from the entity-shape file
/// because route entry-points reference `Cambrian.Generated.World`,
/// which itself imports every entity. Splitting routes out breaks
/// that import cycle. Returns `None` when the entity has no routes.
#[allow(dead_code)]
pub fn gen_entity_routes_file(
    program: &Program,
    entity: &Entity,
    profile: LeanProfile,
) -> Option<String> {
    let graphs = crate::analysis::ProgramGraphs::build(program);
    gen_entity_routes_file_skipping(
        program,
        entity,
        &std::collections::HashSet::new(),
        profile,
        &graphs,
    )
}

/// Like [`gen_entity_routes_file`], but omits `import …Routes` for entity
/// names in `skip_route_imports` (used when those entities' routes are
/// co-emitted in a merged SCC module — B-15).
fn gen_entity_routes_file_skipping(
    program: &Program,
    entity: &Entity,
    skip_route_imports: &std::collections::HashSet<&str>,
    profile: LeanProfile,
    graphs: &crate::analysis::ProgramGraphs,
) -> Option<String> {
    if entity.routes.is_empty() {
        return None;
    }
    let mut out = String::new();
    out.push_str("/-\n");
    out.push_str("  Auto-generated by cambrian-transpiler — Lean target (P3).\n");
    out.push_str(&format!(
        "  Routes for `{}` — `<E>.Local.*` state transitions + World wrappers.\n",
        entity.name,
    ));
    out.push_str("-/\n\n");
    out.push_str("import Cambrian.Prelude\n");
    out.push_str(&format!("import Cambrian.Generated.{}\n", entity.name));
    out.push_str("import Cambrian.Generated.World\n");
    for dep in graphs.send_deps(&entity.name) {
        // Skip entities co-emitted in a merged SCC module — B-15.
        if skip_route_imports.contains(dep.as_str()) {
            continue;
        }
        out.push_str(&format!("import Cambrian.Generated.{}Routes\n", dep));
    }
    if !super::evm::dispatch::gen_dispatch_module(program, profile).is_empty() {
        out.push_str("import Cambrian.Generated.Dispatch\n");
    }
    if !program.extern_entities.is_empty()
        && super::evm::send::route_set_calls_extern(program, entity)
    {
        out.push_str("import Cambrian.Generated.Extern\n");
    }
    out.push('\n');
    out.push_str("set_option linter.unusedVariables false\n\n");
    out.push_str(&super::route::gen_routes_module_with_graphs(
        program, entity, profile, graphs,
    ));
    Some(out)
}

/// Emit every `*Routes.lean` file for `program`, merging cyclic
/// cross-entity route SCCs into one module + thin per-entity stubs (B-15).
pub fn gen_all_routes_files(program: &Program, profile: LeanProfile) -> Vec<(String, String)> {
    let graphs = crate::analysis::ProgramGraphs::build(program);
    let sccs = order_entity_route_sccs(program, &graphs);
    let mut files = Vec::new();
    for scc in sccs {
        let with_routes: Vec<&Entity> = scc.into_iter().filter(|e| !e.routes.is_empty()).collect();
        if with_routes.is_empty() {
            continue;
        }
        if with_routes.len() == 1 {
            if let Some(content) = gen_entity_routes_file_skipping(
                program,
                with_routes[0],
                &std::collections::HashSet::new(),
                profile,
                &graphs,
            ) {
                files.push((
                    format!("Cambrian/Generated/{}Routes.lean", with_routes[0].name),
                    content,
                ));
            }
            continue;
        }
        // Cyclic SCC (size ≥ 2): one merged module + thin stubs so existing
        // `import …XRoutes` sites (Specs, root) keep working without a Lake
        // build cycle.
        let mut names: Vec<&str> = with_routes.iter().map(|e| e.name.as_str()).collect();
        names.sort_unstable();
        let merged_mod = format!("Routes_{}", names.join("_"));
        let scc_set: std::collections::HashSet<&str> = names.iter().copied().collect();
        files.push((
            format!("Cambrian/Generated/{}.lean", merged_mod),
            gen_merged_routes_file(program, &with_routes, &scc_set, profile, &graphs),
        ));
        for e in &with_routes {
            files.push((
                format!("Cambrian/Generated/{}Routes.lean", e.name),
                format!(
                    "/-\n  Auto-generated stub (B-15): routes for `{}` live in\n  \
                     `Cambrian.Generated.{}` to break a cross-entity import cycle.\n-/\n\n\
                     import Cambrian.Generated.{}\n",
                    e.name, merged_mod, merged_mod
                ),
            ));
        }
    }
    files
}

/// Merged `Routes_<A>_<B>_….lean` body for a cyclic entity SCC.
fn gen_merged_routes_file(
    program: &Program,
    entities: &[&Entity],
    scc_names: &std::collections::HashSet<&str>,
    profile: LeanProfile,
    graphs: &crate::analysis::ProgramGraphs,
) -> String {
    let mut out = String::new();
    out.push_str("/-\n");
    out.push_str(
        "  Auto-generated by cambrian-transpiler — Lean target (B-15).\n  \
         Merged routes module for a cyclic cross-entity call graph.\n",
    );
    out.push_str("-/\n\n");
    out.push_str("import Cambrian.Prelude\n");
    for e in entities {
        out.push_str(&format!("import Cambrian.Generated.{}\n", e.name));
    }
    out.push_str("import Cambrian.Generated.World\n");
    // External (acyclic) route deps still imported via their *Routes stubs.
    let mut external: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for e in entities {
        for dep in graphs.send_deps(&e.name) {
            if !scc_names.contains(dep.as_str()) {
                external.insert(dep.to_string());
            }
        }
    }
    for dep in external {
        out.push_str(&format!("import Cambrian.Generated.{}Routes\n", dep));
    }
    if !super::evm::dispatch::gen_dispatch_module(program, profile).is_empty() {
        out.push_str("import Cambrian.Generated.Dispatch\n");
    }
    if !program.extern_entities.is_empty()
        && entities
            .iter()
            .any(|e| super::evm::send::route_set_calls_extern(program, e))
    {
        out.push_str("import Cambrian.Generated.Extern\n");
    }
    out.push('\n');
    out.push_str("set_option linter.unusedVariables false\n\n");
    // Local transitions are state-only and never cross-call — emit them
    // outside `mutual`. Lean rejects `namespace` / `attribute` inside a
    // mutual block; named Local defs after a7de614 made that footgun loud
    // (B-15 lake regression).
    for e in entities {
        out.push_str(&super::route::gen_local_module(program, e, profile));
    }
    // Cross-entity mutual recursion: structured FQN `partial def <E>.Routes.<r>`
    // (no string rewriting of namespaces / attributes).
    out.push_str("mutual\n\n");
    for e in entities {
        out.push_str(
            &super::route::gen_routes_wrappers_fqn_for_mutual_with_graphs(
                program, e, profile, graphs,
            ),
        );
    }
    out.push_str("end\n");
    out
}

/// Strongly connected components of the *entity-level* cross-route
/// dependency graph (typed cross-entity sends), callees-first.
fn order_entity_route_sccs<'a>(
    program: &'a Program,
    graphs: &crate::analysis::ProgramGraphs,
) -> Vec<Vec<&'a Entity>> {
    graphs
        .entity_sccs
        .iter()
        .map(|comp| {
            comp.iter()
                .filter_map(|name| program.entities.iter().find(|e| e.name == *name))
                .collect()
        })
        .collect()
}

// ---------------------------------------------------------------------------
// local items
// ---------------------------------------------------------------------------

fn emit_local_aliases(out: &mut String, entity: &Entity, profile: LeanProfile) {
    for ta in &entity.type_aliases {
        // Always inline. Lean has `abbrev` for transparent aliases;
        // we use it so downstream code never sees the alias.
        out.push_str(&format!(
            "abbrev {} : Type := {}\n",
            ta.name,
            lower_alias_target(ta, entity, profile),
        ));
    }
    if !entity.type_aliases.is_empty() {
        out.push('\n');
    }
}

fn lower_alias_target(ta: &TypeAlias, entity: &Entity, profile: LeanProfile) -> String {
    // Use a tiny local LeanTypeCtx — alias targets reference only
    // primitives + types declared in the same entity (or top level).
    let prog = empty_program_singleton();
    let ctx = LeanTypeCtx::for_entity(
        leak_program(prog),
        &entity.name,
        &entity.records,
        &entity.enums,
        &entity.type_aliases,
        profile,
    );
    lower_type(&ta.ty, &ctx)
}

/// Emit local records + enums in dependency order so a record that
/// references a local enum (or vice versa) is never forward-referenced
/// (Lean rejects forward refs outside a `mutual` block).
fn emit_local_types_ordered(
    out: &mut String,
    program: &Program,
    entity: &Entity,
    profile: LeanProfile,
) {
    let graphs = crate::analysis::ProgramGraphs::build(program);
    for item in graphs.resolve_entity_types(entity) {
        match item {
            super::core::types::TypeItem::Record(rec) => {
                emit_record(out, program, entity, rec, profile)
            }
            super::core::types::TypeItem::Enum(en) => emit_enum(out, entity, en, profile),
        }
    }
}

fn emit_record(
    out: &mut String,
    program: &Program,
    entity: &Entity,
    rec: &Record,
    profile: LeanProfile,
) {
    doc_comment(out, 0, &format!("Local record `{}`.", rec.name));
    out.push_str(&format!("structure {} where\n", lean_local_type_name(&rec.name)));
    let ctx = LeanTypeCtx::for_entity(
        program,
        &entity.name,
        &entity.records,
        &entity.enums,
        &entity.type_aliases,
        profile,
    );
    for f in &rec.fields {
        push_indent(out, 1);
        out.push_str(&format!(
            "{} : {}\n",
            super::core::types::lean_safe_ident(&f.name),
            lower_type(&f.ty, &ctx)
        ));
    }
    let derives = super::core::deceq::instances_filtered(
        ctx.use_predictable_profile,
        true,
        true,
        &["Repr", "Inhabited", "BEq", "DecidableEq"],
    );
    push_deriving(out, ctx.use_predictable_profile, &derives);
    let field_names: Vec<String> = rec
        .fields
        .iter()
        .map(|f| super::core::types::lean_safe_ident(&f.name))
        .collect();
    super::evm::maybe_emit_struct_eq_instances(
        out,
        ctx.use_predictable_profile,
        &lean_local_type_name(&rec.name),
        &field_names,
    );
}

fn emit_enum(out: &mut String, entity: &Entity, en: &EnumDecl, profile: LeanProfile) {
    doc_comment(out, 0, &format!("Local enum `{}`.", en.name));
    out.push_str(&format!("inductive {} where\n", lean_local_type_name(&en.name)));
    let prog = empty_program_singleton();
    let ctx = LeanTypeCtx::for_entity(
        leak_program(prog),
        &entity.name,
        &entity.records,
        &entity.enums,
        &entity.type_aliases,
        profile,
    );
    for v in &en.variants {
        emit_enum_variant(out, &lean_local_type_name(&en.name), v, &ctx);
    }
    let ctors: Vec<(String, usize)> = en
        .variants
        .iter()
        .map(|v| (sanitize_variant(&v.name), v.fields.len()))
        .collect();
    // Data-carrying enum: drop the matcher-minting `deriving BEq` and emit an
    // explicit Bool matrix (P4, see `lean_pure::emit_top_level_enum`); nullary
    // enum keeps `deriving BEq` (a `ctorIdx` comparison — predictable).
    let is_data = ctors.iter().any(|(_, arity)| *arity > 0);
    let derives = super::core::deceq::instances_filtered(
        ctx.use_predictable_profile,
        true,
        is_data,
        &["Repr", "Inhabited", "BEq", "DecidableEq"],
    );
    push_deriving(out, ctx.use_predictable_profile, &derives);
    super::evm::maybe_emit_enum_eq_instances(
        out,
        ctx.use_predictable_profile,
        &lean_local_type_name(&en.name),
        &ctors,
        is_data,
    );
}

fn emit_enum_variant(out: &mut String, _enum_name: &str, v: &EnumVariant, ctx: &LeanTypeCtx<'_>) {
    push_indent(out, 1);
    if v.fields.is_empty() {
        out.push_str(&format!("| {}\n", sanitize_variant(&v.name)));
    } else {
        let parts: Vec<String> = v.fields.iter().map(|t| lower_type(t, ctx)).collect();
        out.push_str(&format!(
            "| {} : {} → {}\n",
            sanitize_variant(&v.name),
            parts.join(" → "),
            _enum_name,
        ));
    }
}

fn emit_constants(out: &mut String, program: &Program, entity: &Entity, profile: LeanProfile) {
    if entity.constants.is_empty() {
        return;
    }
    let type_ctx = LeanTypeCtx::for_entity(
        program,
        &entity.name,
        &entity.records,
        &entity.enums,
        &entity.type_aliases,
        profile,
    );
    let expr_ctx = LeanExprCtx {
        type_ctx: LeanTypeCtx {
            program: type_ctx.program,
            proof_helpers: type_ctx.proof_helpers,
            use_nat_numerics: type_ctx.use_nat_numerics,
            overflow_panic: type_ctx.overflow_panic,
            use_predictable_profile: type_ctx.use_predictable_profile,
            deterministic_addresses: type_ctx.deterministic_addresses,
            entity_name: type_ctx.entity_name,
            local_records: type_ctx.local_records,
            local_enums: type_ctx.local_enums,
            local_aliases: type_ctx.local_aliases,
        },
        entity,
        local_enums: &entity.enums,
        pure_fns: &program.pure_fns,
        lets: HashSet::new(),
        route_params: HashSet::new(),
        route_name: None,
        phase_name: None,
        route_arg_names: vec![],
        in_transform: false,
        state_var: "s".to_string(),
        derived_helpers: HashSet::new(),
        world_var: None,
        instance_var: None,
        qualified_instances: std::collections::HashMap::new(),
        deploy_bindings: std::collections::HashMap::new(),
        hashmap_idents: std::collections::HashSet::new(),
        nat_idents: std::collections::HashSet::new(),
        trace_acc_var: None,
        expected_bitvec_width: None,
        expected_signed: None,
        expected_collection: None,
        msg_sender_override: None,
        pure_fn: None,
    };
    for c in &entity.constants {
        out.push_str(&format!(
            "def {} : {} := {}\n",
            c.name,
            lower_type(&c.ty, &type_ctx),
            gen_expr(&c.value, &expr_ctx),
        ));
    }
    out.push('\n');
}

// ---------------------------------------------------------------------------
// helpers — leak a tiny empty Program so we can build a LeanTypeCtx for
// alias-target / enum lowering without threading the program everywhere.
// Safe because the leaked allocation is small and per-call.
// ---------------------------------------------------------------------------

fn empty_program_singleton() -> Program {
    Program {
        imports: vec![],
        file_imports: vec![],
        pure_fns: vec![],
        type_aliases: vec![],
        records: vec![],
        enums: vec![],
        entities: vec![],
        extern_entities: vec![],
        tests: vec![],
        properties: vec![],
        fuzz_tests: vec![],
        invariants: vec![],
        events: vec![],
        errors: vec![],
        libraries: vec![],
        using_decls: vec![],
    }
}

fn leak_program(p: Program) -> &'static Program {
    Box::leak(Box::new(p))
}
